### ISSUE TITLE
standardize and simplify package data sets and column names

### ISSUE THREAD

**Issue by eosnas** [USFWS/AKaerial#9]
Data column names are not case-standardized or share an intuitive naming convention. For example, the point estimate for indicated breeding pair is ibb in $combined and ibbtotal.est in $expanded.table or $output.table, and in the latter ibb referent to the observe number of ibb. Likewise, standard errors have different naming conventions.

Also, there seems to be a lot of unnecessary information in the data table, e.g., the 'cov' or cross product terms.

**Comment by cfrost3** [comment]
merge with issue 21
